[package]
name = "text2bits"
version = "0.1.1"
authors = ["Jacob Pembleton <jacobpembleton@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
